import {
  type Candidate,
  type Profile,
  type Report,
  SCHEMA_VERSION,
} from "./index";

export const demoProfile: Profile = {
  id: "profile_demo",
  version: 1,
  confirmed: true,
  mode: "demo",
  name: "Sunday Supply",
  url: "https://sunday-supply.example",
  category: "Specialty coffee",
  audience: "Thoughtful home brewers who care about the everyday ritual",
  geography: "North America",
  goal: "Find complementary brand partnerships",
};
const make = (
  id: string,
  name: string,
  category: string,
  tagline: string,
  tone: string,
  mark: string,
  score: number,
  idea: string,
  reason: string,
): Candidate => ({
  id,
  name,
  domain: `${name.toLowerCase().replace(/[^a-z]/g, "")}.example`,
  category,
  tagline,
  tone,
  mark,
  score,
  idea,
  reason,
  description: tagline,
  confidence: score > 85 ? "High" : "Medium",
  caveat:
    "Illustrative fit only. Confirm audience overlap, Shopify status, and fulfillment capacity before making contact.",
  evidenceIds: [`${id}_catalog`, `${id}_review`],
  components: [
    { label: "Complementary customer job", score: score + 2, weight: 30 },
    { label: "Audience overlap", score: score - 2, weight: 20 },
    { label: "Price & positioning", score, weight: 15 },
    { label: "Operational fit", score: score - 3, weight: 15 },
    { label: "Evidence quality", score: score - 1, weight: 10 },
    { label: "Partnership novelty", score: score + 4, weight: 10 },
  ],
});
const collaborators = [
  make(
    "form",
    "Form & Field",
    "Ceramics & home",
    "Good mornings, made by hand.",
    "lilac",
    "ceramic",
    94,
    "The slow morning bundle",
    "Handmade mugs meet small-batch coffee: complementary products for the same daily ritual.",
  ),
  make(
    "daybreak",
    "Daybreak",
    "Brewing essentials",
    "A better brew starts here.",
    "peach",
    "kettle",
    91,
    "A first-brew starter kit",
    "Approachable brewing tools give new coffee drinkers a natural entry point to your beans.",
  ),
  make(
    "oat",
    "Oat & Honey",
    "Pantry & provisions",
    "A little sweeter. A lot better.",
    "yellow",
    "jar",
    87,
    "Your weekend, delivered",
    "Breakfast provisions pair naturally with a coffee subscription and a shared weekend story.",
  ),
  make(
    "chapter",
    "Another Chapter",
    "Books & lifestyle",
    "Make a little time for yourself.",
    "blue",
    "book",
    84,
    "The Sunday reading club",
    "A book-and-coffee discovery box creates a repeatable ritual for both communities.",
  ),
  make(
    "linen",
    "Soft Hours",
    "Home & textiles",
    "Everyday things, thoughtfully made.",
    "sage",
    "textile",
    82,
    "A table worth slowing down for",
    "Table linens and coffee create an approachable shared table-setting campaign.",
  ),
  make(
    "morrow",
    "Morrow Studio",
    "Scent & atmosphere",
    "Set the mood for a slower day.",
    "pink",
    "candle",
    79,
    "The off-duty collection",
    "A coffee-and-candle gifting set connects two sensory rituals without product overlap.",
  ),
];
const competitors = [
  make(
    "weekend",
    "Weekend Roasters",
    "Specialty coffee",
    "Small-batch beans. Big weekend energy.",
    "peach",
    "bag",
    93,
    "Make origin information easier to explore",
    "A direct alternative serving home brewers with single-origin beans and subscriptions.",
  ),
  make(
    "common",
    "Common Ground",
    "Everyday coffee",
    "Your daily cup, done well.",
    "sage",
    "ceramic",
    88,
    "Show what makes your subscription flexible",
    "Subscription convenience and accessible pricing address the same daily coffee need.",
  ),
  make(
    "ritual",
    "Ritual House",
    "Coffee & lifestyle",
    "More than a morning routine.",
    "lilac",
    "kettle",
    85,
    "Give your brewing story a clearer home",
    "Lifestyle-led coffee competes for a similar audience and gifting occasions.",
  ),
  make(
    "north",
    "Northline Coffee",
    "Specialty coffee",
    "Roasted with a sense of place.",
    "blue",
    "bag",
    83,
    "Explain your sourcing in plain language",
    "Origin-focused positioning overlaps with shoppers seeking traceability.",
  ),
  make(
    "steep",
    "Steep Society",
    "Tea & rituals",
    "A different kind of daily cup.",
    "yellow",
    "jar",
    76,
    "Explore the low-caffeine occasion",
    "Premium tea can substitute for the afternoon coffee ritual.",
  ),
].map((c, i) => ({
  ...c,
  type: (i === 4
    ? "substitute"
    : i === 2
      ? "adjacent"
      : "direct") as Candidate["type"],
  components: [
    { label: "Product / job overlap", score: c.score, weight: 30 },
    { label: "Audience overlap", score: c.score, weight: 20 },
    { label: "Price overlap", score: c.score, weight: 15 },
    { label: "Positioning similarity", score: c.score, weight: 15 },
    { label: "Discourse recency", score: c.score, weight: 10 },
    { label: "Source diversity", score: c.score, weight: 10 },
  ],
}));

export function fixtureReport(
  profile = demoProfile,
  id = "report_demo",
): Report {
  const evidence = [...collaborators, ...competitors].flatMap((c) => [
    {
      id: `${c.id}_catalog`,
      title: `${c.name} · sample storefront`,
      sourceType: "First-party catalog",
      span: `${c.name} offers ${c.category.toLowerCase()}. ${c.tagline} This is a fictional catalog excerpt created for the product demo.`,
      publishedAt: "2026-09-18",
      url: null,
      synthetic: true,
    },
    {
      id: `${c.id}_review`,
      title: `${c.name} · sample community discussion`,
      sourceType: "Independent discussion",
      span: `“I like having thoughtful, well-made things as part of my morning routine. A simple bundle would make a lovely gift.” Fictional customer comment used to demonstrate evidence presentation.`,
      publishedAt: "2026-09-16",
      url: null,
      synthetic: true,
    },
  ]);
  evidence.push({
    id: "store_catalog",
    title: "Sunday Supply · sample brand profile",
    sourceType: "Merchant profile",
    span: "The demo store sells small-batch, single-origin coffee and flexible subscriptions, with detailed sourcing notes. Its sample catalog has a narrow range of accessories and no entry-level brew kit.",
    publishedAt: "2026-09-19",
    url: null,
    synthetic: true,
  });
  const item = (
    id: string,
    title: string,
    description: string,
    evidenceIds: string[],
    observation = false,
  ) => ({
    id,
    title,
    description,
    evidenceIds,
    confidence: "Medium",
    claimType: observation ? ("observation" as const) : ("inference" as const),
  });
  return {
    id,
    schemaVersion: SCHEMA_VERSION,
    profile,
    status: "completed",
    phase: "synthesizing",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    mode: "demo",
    warning: null,
    collaborators,
    competitors,
    evidence,
    themes: [
      {
        id: "praise",
        kind: "Praise",
        title: "The ritual matters as much as the coffee",
        description:
          "The sample comments connect well-made products with an enjoyable morning routine.",
        mentions: 3,
        evidenceIds: ["form_review", "common_review", "ritual_review"],
      },
      {
        id: "complaint",
        kind: "Complaint",
        title: "Evidence gap: subscription frustrations",
        description:
          "No complaint evidence is included in this fixture. Collect independent comments before making a claim.",
        mentions: 0,
        evidenceIds: [],
      },
      {
        id: "switching",
        kind: "Switching trigger",
        title: "Evidence gap: why customers change brands",
        description:
          "This fixture does not establish switching behavior. More independent research is needed.",
        mentions: 0,
        evidenceIds: [],
      },
      {
        id: "unmet",
        kind: "Unmet need",
        title: "A thoughtful gift, without the extra decisions",
        description:
          "Two sample comments suggest interest in an easy gifting bundle. Treat this as an early hypothesis.",
        mentions: 2,
        evidenceIds: ["form_review", "oat_review"],
      },
    ],
    swot: {
      strengths: [
        item(
          "s1",
          "A clear everyday ritual",
          "The demo brand positions its coffee around a considered daily routine.",
          ["store_catalog"],
          true,
        ),
        item(
          "s2",
          "A recurring relationship",
          "Flexible subscriptions create a repeat purchase offering.",
          ["store_catalog"],
          true,
        ),
        item(
          "s3",
          "A sourcing story to share",
          "Detailed origin notes give the brand concrete material for educational content.",
          ["store_catalog"],
          true,
        ),
      ],
      weaknesses: [
        item(
          "w1",
          "A narrow accessory range",
          "The sample catalog has few complementary brewing products.",
          ["store_catalog"],
          true,
        ),
        item(
          "w2",
          "No beginner brew kit",
          "The demo store has no entry-level kit to simplify a first purchase.",
          ["store_catalog"],
          true,
        ),
        item(
          "w3",
          "Gifting needs a clearer offer",
          "A coffee-only range may make it harder to serve shoppers seeking a complete gift.",
          ["store_catalog", "form_review"],
        ),
      ],
      opportunities: [
        item(
          "o1",
          "Make the whole morning",
          "Test a ceramic-and-coffee bundle with a complementary maker.",
          ["form_catalog", "form_review"],
        ),
        item(
          "o2",
          "Meet the next home brewer",
          "Explore a brewing-tool partnership to reduce first-purchase friction.",
          ["daybreak_catalog", "store_catalog"],
        ),
        item(
          "o3",
          "Own a weekend occasion",
          "A breakfast collaboration could create a new gifting occasion.",
          ["oat_catalog", "oat_review"],
        ),
      ],
      threats: [
        item(
          "t1",
          "Similar subscription offers",
          "Other sample brands offer comparable coffee subscriptions.",
          ["common_catalog", "weekend_catalog"],
        ),
        item(
          "t2",
          "Competing ritual stories",
          "Lifestyle-led coffee brands occupy a similar positioning space.",
          ["ritual_catalog", "ritual_review"],
        ),
        item(
          "t3",
          "Alternatives beyond coffee",
          "Premium tea could serve a similar daily ritual; validate actual switching behavior.",
          ["steep_catalog", "steep_review"],
        ),
      ],
    },
    actions: [
      {
        title: "Test a coffee + ceramic bundle",
        experiment:
          "Show a bundle concept to 20 current customers. Continue only if at least 5 request a launch notification.",
        effort: "1 week · low effort",
        evidenceIds: ["form_catalog", "form_review"],
      },
      {
        title: "Help beginners find their first brew",
        experiment:
          "Test a brew-kit concept with 10 first-time buyers. Look for at least 3 who prefer it to beans alone.",
        effort: "1 week · medium effort",
        evidenceIds: ["daybreak_catalog", "store_catalog"],
      },
      {
        title: "Explore the weekend gifting occasion",
        experiment:
          "Interview 8 gift shoppers. Drop the idea if fewer than 2 describe an unmet breakfast-gifting need.",
        effort: "3 days · low effort",
        evidenceIds: ["oat_catalog", "oat_review"],
      },
    ],
  };
}
